fix: cluster create with empty oidc_issuer_ca_cert or oidc_issuer_url
Previously creating clusters with an empty oidc_issuer_ca_cert or
oidc_issuer_url attribute failed with the following:

  Error: Provider produced inconsistent result after apply

  When applying changes to cofide_connect_cluster.right, provider
  "provider[\"registry.terraform.io/cofide/cofide\"]" produced an unexpected
  new value: .oidc_issuer_ca_cert: was cty.StringVal(""), but now null.

  This is a bug in the provider, which should be reported in the provider's
  own issue tracker.

This change fixes the issue by setting the values to an empty string (or
base64 encoding thereof).

Fixes: #40